# Generated by Django 4.1.4 on 2022-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billmanagement", "0002_alter_customer_email_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
