# Generated by Django 4.1.4 on 2023-01-25 05:22

import apps.subscription.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="to_date",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1984),
                    apps.subscription.models.max_value_current_year,
                ],
                verbose_name="year",
            ),
        ),
    ]
